# PortugÃªs
# Menu labels
menu_title = """
    ##########################################################
    **********************************************************
    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ•—   â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—     â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
    â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â•šâ•â•â–ˆâ–ˆâ–ˆâ•”â•    â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
    â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ–ˆâ•”â•     â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•
    â–ˆâ–ˆâ•‘â–„â–„ â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ–ˆâ•”â•      â–ˆâ–ˆâ•‘â–„â–„ â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â• â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
    â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—    â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘
    â•šâ•â•â–€â–€â•â•  â•šâ•â•â•â•â•â• â•šâ•â•â•šâ•â•â•â•â•â•â•     â•šâ•â•â–€â–€â•â• â•šâ•â•     â•šâ•â•  â•šâ•â•

    **********************************************************
    ##########################################################
    ğŸ²ğŸ†ğŸ¤“â­ QPR â­ğŸ²ğŸ†ğŸ¤“
    **********************************************************

    ğŸ® Quiz de perguntas e respostas no Terminal sobre programaÃ§Ã£o ğŸ®
    """
menu_info = """

    O QPR Ã© um quiz de perguntas e respostas sobre programaÃ§Ã£o e TI,
foi feito em Python 3.12 para Terminais como Bash, Zash ou Powershell.
Utilize as setas do teclado para navegar no menu principal e ENTER para confirmar. Para as
perguntas, digite a alternativa escolhida e aperte ENTER.
    O cÃ³digo fonte Ã© [italic]open source[/] e mais informaÃ§Ãµes estÃ£o disponÃ­veis no GitHub para acesso
atravÃ©s do link https://github.com/Cybermedes/QPR-quiz-game.
"""
menu_goodbye = "ğŸ‘‹ Tchau e atÃ© a prÃ³xima!"
menu_instruction_one = "(Use as setas e aperte ENTER)"
menu_instruction_two = "Pressione qualquer tecla para voltar ao menu principal..."
menu_version = "Version: Beta"
menu_options = ["Jogar", "Sobre", "Sair"]
menu_message = "Selecione uma das opÃ§Ãµes abaixo:"

# Quiz labels
quiz_right_answer = "\nâœ… â­ Resposta Correta! â­\n"
quiz_wrong_answer = "\nâŒ A resposta certa Ã© [bold green]{}[/], nÃ£o [bold red]{}[/].\n"
quiz_error_message = "ğŸš« Por favor responda com [cyan]{}[/]"
quiz_question = "\nQuestÃ£o {}:"
quiz_user_input = "\nQual Ã© a resposta? "
quiz_instruction = "Pressione qualquer tecla para continuar..."
quiz_final_score = """\nVocÃª acertou [bold underline]{}[/] perguntas
de um total de [bold underline]{}[/] perguntas."""
quiz_play_again = "\nJogar novamente [s/n]? "
quiz_invalid_option = "ğŸš« Por favor responda com [green]'s'[/] para sim ou [red]'n'[/] para nÃ£o"
quiz_no_database = "âš ï¸ O arquivo 'questions.toml' nÃ£o foi encontrado âš ï¸"
quiz_aborted_message = "\n\nVocÃª abandonou o jogo!!"
